### PR TITLE
Api

### PR DESCRIPTION
**Pull request by Luleherll**
This will merge the API branch containing the Fast-Food-Fast API for adding, updating and retrieving of orders.<br/>
Heroku url is here:  https://lule-fast-food.herokuapp.com/

### CODE REVIEW

**Comment by ekumamait** [comment]
Nice work Herman just fix your naming conventions for the application and also I suggest you use datetime instead of getting date from json

**Comment by Phionamary** [comment]
I am with @ekumamait on the date thing.  It would make your work simpler.  
Otherwise,  good work Herman

**Comment by Luleherll** [comment]
@Phii @ekumamait  the date thing is not what you have in mind of `the time that the order has been sent`. its the time that the customer wants the delivery in. i dont think `datetime` is suitable in a situation this

**Comment by ekumamait** [comment]
That makes sense but in that case doesn’t the app dictate delivery time
based on location cause when you make an order they’ll have to make the
meal and then deliver it to the customer?

**Pull request merged**
