### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Luleherll**
This will merge the feature branch which includes the UI for the Fast-Food-Fast app to develop.
## https://luleherll.github.io

### CODE REVIEW

**Comment by mozzy22** [comment]
its cool. u can add some JS validation for user input..and probably some responsiveness

**Comment by mozzy22** [comment]
i also cant see the home page , logut, links, wen loged in

**Comment by Luleherll** [comment]
thanks, i going to fix it

**Comment by edmondsylar** [comment]
This is fine I think it's only the responsiveness missing but generally all is fine

**Comment by NtaleShadik** [comment]
yeah its fine though some links aren't working

**Comment by Kasulejoseph** [comment]
to be frank.. yo background color is not good , it makes the all project nasty actually. i would request
yo to do something one it.. and give an action to the `order now` button.

**Comment by walimike** [comment]
Your UI lacks responsiveness(which is not compulsory btw) and you have deadlinks, work on that, otherwise, good job

**Comment by Phionamary** [comment]
@lule...  
In my opinion,  i think as long you have what is required,  it is okay. 
Responsiveness just pushes you to excellence,  which is what you are striving for.  Much as it is not a requirement for challenge 1,  I think you should try as much as possible  to get your links to actually do what they should be doing.

**Comment by Luleherll** [comment]
let me see what to do on that. time,time,time

**Comment by okellogabrielinnocent** [comment]
Your work is good just use nice colors and add log out links

**Comment by walimike** [comment]
This is good, about responsiveness, it varies from one pc to another depending on the screen size, so a UI may be goodlooking on one pc and really ugly on another, the hack would be using percentages in your css I guess rather than fixing the height of divs to something static.

**Pull request merged**
